---

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate

- name: Install psycopg2
  pip: virtualenv={{ virtualenv_path }} name=psycopg2
  tags: packages
