---

- name: Install base packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - python-pip
    # required for psycopg2
    - libpq-dev
    - python-dev
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv state=latest
  tags: packages
